### ISSUE TITLE
Game crashes when trying to open any level

### ISSUE THREAD

**Issue by RueOfficial** [Fleeym/nongd#12]
Crash Logs:
[2024-01-21_22-01-18.log](https://github.com/Fleeym/nongd/files/14004258/2024-01-21_22-01-18.log)

Note: This only happens when activating this specific mod, i have not tried yet if it crashes if i disable the other mods, i will try it later and will update this issue if i find anything

**Comment by spookwav** [comment]
same happens to me. tried disabling other mods and it only happens when jukebox is active

**Comment by RueOfficial** [comment]
Okay so i disabled all other mods except Jukebox, (Not uninstall them, just disable them through Geode)

It still crashes when trying to open any level

Crash Logs:
[2024-01-21_23-16-29.log](https://github.com/Fleeym/nongd/files/14004652/2024-01-21_23-16-29.log)

**Comment by yoiryosaturn** [comment]
Yes this is very problematic. Your mod is like the only one that does not work with Geode

**Comment by Fleeym** [comment]
fixed in latest version (v2.0.1)

**Comment by spookwav** [comment]
> Okay so i disabled all other mods except Jukebox, (Not uninstall them, just disable them through Geode)
> 
> It still crashes when trying to open any level
> 
> Crash Logs: [2024-01-21_23-16-29.log](https://github.com/Fleeym/nongd/files/14004652/2024-01-21_23-16-29.log)

this also happened to me when using the prism mod menu before i installed jukebox.
