### ISSUE TITLE
Crash when opening levels with official songs

### ISSUE THREAD

**Issue by Khronophobia** [Fleeym/nongd#13]
Crash when opening Silent Clubstep, Level Easy, and Demon Park. One thing they had in common is that they use official levels.

Crash log: [2024-01-22_14-09-23.log](https://github.com/Fleeym/nongd/files/14006461/2024-01-22_14-09-23.log)

**Comment by Fleeym** [comment]
will look into it in a bit

**Comment by Jumperbumper** [comment]
I've been getting crashes on levels with custom songs too. Every level I try to view crashes the game

**Comment by Fleeym** [comment]
official level song crash should be fixed in the new release (v2.1.0)
