### ISSUE TITLE
Crash when opening the level page of any level

### ISSUE THREAD

**Issue by Aktimoose** [Fleeym/nongd#14]
My game just instantly crashes when I click onto any custom level's page, even without any other mods loaded. This is the case even if I clear my mod save data from %localappdata%/GeometryDash/geode/mods.

Crashlog:
[2024-01-22_09-04-26.log](https://github.com/Fleeym/nongd/files/14007596/2024-01-22_09-04-26.log)

This is on Windows 11, using mod version 2.0.0, and Geode 2.0.0-beta.4.

**Comment by Fleeym** [comment]
Hello, update to v2.0.1, problem has been fixed

**Comment by Aktimoose** [comment]
Oops did not see the update in-game loI, works fine now 👍
