### ISSUE TITLE
Cannot press Options or Pause in Editor with Jukebox Enabled

### ISSUE THREAD

**Issue by j-wisn** [Fleeym/nongd#18]
When using Jukebox with Geode, the Options menu and the Pause menu buttons do nothing. With Jukebox disabled, they work as intended.

**Comment by Fleeym** [comment]
I can't seem to replicate that. Can you give me more details? Jukebox doesn't edit anything regarding those buttons, so I don't really see it being because of it.

**Comment by j-wisn** [comment]
The issue seems to have miraculously solved itself. I don’t know why, or how, but the issue _was_ legitimate at the time of posting. It is working fine now with no issues, so it was probably something else. Closing :)
