### ISSUE TITLE
Cannot import MP3

### ISSUE THREAD

**Issue by Desuki7** [Fleeym/nongd#19]
It appears an error that tells me to use a callback version
![Screenshot_20240123_022959_Geode](https://github.com/Fleeym/nongd/assets/149386907/0dbe6279-e502-4079-aa4f-98d6ea382d28)

**Comment by Fleeym** [comment]
imports on android haven't been tested, i'll look into it

**Comment by xorpix** [comment]
Can confirm, on the latest version (2.1.5) the game crashes after I select mp3, input the song's author and name and press Add.

**Comment by Fleeym** [comment]
if you are on Android >13 enable media permissions for Geode in the app settings

**Comment by Desuki7** [comment]
Hello! It works without crashes :)
