### ISSUE TITLE
"Failed to fetch song from File Hub"

### ISSUE THREAD

**Issue by millionsofplayers** [Fleeym/nongd#4]
[Here's an image of the error.](https://files.catbox.moe/xp01vf.png) I don't know what's causing this so I don't have much to add. I'm using the latest version of geode and downloaded this directly from the game.

**Comment by Aktimoose** [comment]
Developer console logs just say `[nongd]: Fetch failed: HTTP response code said error` with nothing further

**Comment by Fleeym** [comment]
Seems the Song File Hub API is redirecting to their main page automatically. I'll leave a comment here when it works again.

**Comment by Fleeym** [comment]
Yeah so, they did an update to their API. I will have to update the mod to use it. Expect it in a few days.

**Comment by Fleeym** [comment]
Mod updated, update it to v1.0.4 and SFH should work now!
